In [14]:
import json
from pathlib import Path
import tensorflow as tf
import src.data.build_dataset as build_dataset
import src.data.input_pipeline as input_pipeline
import importlib
import src.models.transformer.metrics as metrics
import src.models.transformer.utils as utils

file = [r"D:\David\Škola\outfit-generation\data\processed\tfrecords\fitb-features.tfrecord"]
importlib.reload(input_pipeline)
importlib.reload(utils)
dataset = input_pipeline.get_fitb_dataset(file, True, utils.build_category_lookup_table()).take(10)

for x in dataset:
    inputs, input_categories, targets, target_categories, target_position = x
    
    print(input_categories)
    print(target_categories)
    print(target_position)


tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
tf.Tensor([1 1 5 1], shape=(4,), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([0 8 2 3 5 5 4 4], shape=(8,), dtype=int64)
tf.Tensor([4 9 5 5], shape=(4,), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([0 1 2 3 5 9], shape=(6,), dtype=int64)
tf.Tensor([9 4 1 3], shape=(4,), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([0 4 5 5], shape=(4,), dtype=int64)
tf.Tensor([9 4 4 5], shape=(4,), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([0 1 8 2 4 4 9 9], shape=(8,), dtype=int64)
tf.Tensor([3 1 9 3], shape=(4,), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([0 1 2 3 9 9], shape=(6,), dtype=int64)
tf.Tensor([4 8 4 2], shape=(4,), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([0 1 8 4 4 9], shape=(6,), dtype=int64)
tf.Tensor([2 1 9 5], shape=(4,), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([0 1 2 3 3 4 2], shape=(7,), dtype=int64)
tf.Tensor([9 3 3 9], s